CREATE TABLE IF NOT EXISTS saas_agro_public_workspaces (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  workspace_key VARCHAR(40) NOT NULL,
  version VARCHAR(20) NOT NULL DEFAULT 'v1',
  workspace_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_saas_agro_public_workspace_key (workspace_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
